### ISSUE TITLE
Seagate Barracuda 510 not recognized.

### ISSUE THREAD

**Issue by Murianwind** [hexagon-oss/openhardwaremonitor#17]
I have a Seagate Barracuda 510 connected to my ASUS PN 50, but it is not recognized. Is there any way I can try?

**Comment by pgrawehr** [comment]
How is it attached (USB, Sata, ...) ? Please provide the log file. It is named OHM<date> in your temp folder.

**Comment by Murianwind** [comment]
I connected the SSD to the nvme. There is no temp folder in the folder where you installed OHM. Is there an option to create a log file? How can i get the log file?

**Comment by pgrawehr** [comment]
I'm sorry, I forgot that I never actually published the build with logging support. 

Go to https://github.com/hexagon-oss/openhardwaremonitor/releases/tag/v0.9.7-alpha10 and download the latest release. Maybe this even fixes your problem.

**Comment by Murianwind** [comment]
I have confirmed that the problem has been resolved. Thanks for the update.
