### ISSUE TITLE
Problem with i5-10400 CPU

### ISSUE THREAD

**Issue by qiangqiang101** [hexagon-oss/openhardwaremonitor#24]
I have this error on repeat when calling `hardware.Update()` on a i5-10400 CPU
9:07 AM: Object reference not set to an instance of an object.   at OpenHardwareMonitor.Hardware.CPU.GenericCPU.Update() in D:\Projects\openhardwaremonitor\OpenHardwareMonitorLib\Hardware\CPU\GenericCPU.cs:line 273
   at OpenHardwareMonitor.Hardware.CPU.IntelCPU.Update() in D:\Projects\openhardwaremonitor\OpenHardwareMonitorLib\Hardware\CPU\IntelCPU.cs:line 431
   at ResMon.frmMonitor.Monitor() in E:\Users\Bartholomew\Documents\GitHub\BigBro-Monitor\ResMon\frmMonitor.vb:line 122

**Comment by pgrawehr** [comment]
Hi @qiangqiang101 
You seem to be using the library directly. The crash you see is probably due to an incorrectly filled `cpuid` array when constructing the `IntelCPU` instance. Can you show the call to the `IntelCPU` constructor?

**Comment by pgrawehr** [comment]
Closing this, as it was probably an error in library usage. 

Feel free to reopen and provide additional details, if required.
