### ISSUE TITLE
Radeon sensors gone

### ISSUE THREAD

**Issue by oomek** [hexagon-oss/openhardwaremonitor#30]
I've lost all my AMD Radeon Vega 64 sensors after updating Windows 11 to the recent beta build and then updating Radeon driver. When I uninstall Radeon driver and use stock Windows driver the sensors are back. Do you have any idea what is going on?

[OpenHardwareMonitor.Report.txt](https://github.com/hexagon-oss/openhardwaremonitor/files/8446484/OpenHardwareMonitor.Report.txt)

**Comment by pgrawehr** [comment]
@oomek Can you look at the log file? It is called "OHM<TimeStamp>.log" and sits in the user temp directory. Maybe you find something interesting there. If not, I'd need to improve the logging for that problem first.

**Comment by oomek** [comment]
[OHM_2022-04-11.log](https://github.com/hexagon-oss/openhardwaremonitor/files/8463157/OHM_2022-04-11.log)

**Comment by oomek** [comment]
There is something wrong with nvme aswell, but that's concerns me less. When I leave just CPU and GPU enabled the log is clean.

**Comment by pgrawehr** [comment]
Ok, guess I first need to extend the log for errors related to the GPU. The NVMe errors are related to the fact that not all disks support the same interfaces, even from the same vendor. It appears these haven not been properly standardized.

**Comment by pgrawehr** [comment]
I just had a similar issue. The Radeon sensors where gone, but after I installed the latest AMD Adrenalin package (not only the driver) it works again. This was on Windows 10, though. I'll try to improve the logging, so that such problems should at least leave a correct trace in the log (Unfortunately, the code contains a lot of "Ignore the error and silently continue anyway" cases)

**Comment by oomek** [comment]
Log file from 0.10.2-alpha1
[OHM_2022-04-27.log](https://github.com/hexagon-oss/openhardwaremonitor/files/8567984/OHM_2022-04-27.log)

**Comment by oomek** [comment]
Surprise. In the latest Windows 11 build 22610 AMD sensors magically appeared again. Go figure Microsoft :D
