### ISSUE TITLE
  Show Gadget 

### ISSUE THREAD

**Issue by Reibeiro2017** [hexagon-oss/openhardwaremonitor#37]
![Sem título](https://user-images.githubusercontent.com/109174594/178573825-bce85518-0696-46f8-acda-3aa1c73eb5e8.png)
Hello everyone,
I want to thank everyone for their work.
when right-clicking Gadget in version v0.9.6 this adjustment options appeared, I can't know in version 0.10.2-alpha1.
how do i do?

thank you all

**Comment by pgrawehr** [comment]
@Reibeiro2017 Hi and sorry I haven't seen this report earlier. 

The issue is actually fixed on master, but there has not been a release which includes this fix yet. I'll ping you when that happens.

**Comment by Reibeiro2017** [comment]
@pgrawehr pgrawehr
hello, I'm grateful and eager for the correction.Thanks

**Comment by pgrawehr** [comment]
@Reibeiro2017 The new Version is available here: https://github.com/hexagon-oss/openhardwaremonitor/releases/tag/v0.10.3-alpha1

Note that the option "show gadget topmost" has been moved to the main options menu, because it was obviously not accessible if the window was not visible.

**Comment by Reibeiro2017** [comment]
@pgrawehr, thank you so much! I already installed the new version... it's very good. thanks... Hugs!
