### ISSUE TITLE
WMI root entry OpenHardwareMonitor don't removed.

### ISSUE THREAD

**Issue by T-Troll** [hexagon-oss/openhardwaremonitor#38]
How it works now:
- Then started, OHM create WMI namespace and classes to provide data
- Even if not active or removed, namespace still into WMI.

What i asking for:
- Remove WMI namespace then data is not available (at application quit).

**Comment by pgrawehr** [comment]
Which version are you using? The latest version does not use WMI at all any more (but a webservice instead)

**Comment by T-Troll** [comment]
Yes, i check the old one....

It's hard to hear you remove WMI support - it widely used by many 3rd-party applications, including mine [AlienFX-Tools](https://github.com/T-Troll/alienfx-tools).
So we stuck at base OHM version....

Is it any way to return it back?

**Comment by pgrawehr** [comment]
I don't think so. It was just unreliable. Often, without any visible reason, the sensors where not available on WMI, and then you reinstalled the application (or rebuilt it, or did some other no-change update) it worked again. It's probably better if you update your client code. There's a C# client available as part of the `Iot.Device.Bindings` package (from https://github.com/dotnet/iot). It uses just a simple web request with a json reply, which should also be fairly straight forward in C++.

**Comment by T-Troll** [comment]
Ok, i got your point.

But, anyway, you broke all 3rd-party Windows apps and scripts who use it.

**Comment by pgrawehr** [comment]
I can consider it, but I mostly made that change for our own use case, where the existing WMI solution just didn't work reliably. Of course, I do not know how many libraries and scripts use the WMI interface.

**Comment by alexxxdev** [comment]
webservice does not replace WMI in any way ((

**Comment by T-Troll** [comment]
@alexxxdev It's play against Occam's razor in many cases as well.
PS: I see some guys even port WMI to Linux to use some proprietary ACPI methods. Keyword: Clevo.

**Comment by pgrawehr** [comment]
> webservice does not replace WMI in any way ((

Why not? It's much more flexible and system independent.

IIRC one of the reasons for removal was that .Net6.0 no longer supports the WMI api, at least not in the way it was used before.

**Comment by T-Troll** [comment]
> Why not? It's much more flexible and system independent.

Patrick, do you remember about Linux way? Don't try to be universal, try to do small task good!
WMI is a Windows way to do so.

> .Net6.0 no longer supports the WMI api

.Net for portability? Hmmm... Looks strange.
I check it, yes, seems like Microsoft.Management.Infrastructure is obsolete.
Bad news for c# coders, seems like MS fade it away.

**Comment by pgrawehr** [comment]
I am not the guy that always wants to be universal. But if the universal solution is the easiest, and the existing, non-universal solution is deprecated, there's no reason to try to write some hack to stick with the old way.

**Comment by T-Troll** [comment]
Patrick, thank you for your comments!
I switch to [Libre](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) OHM clone, they still support WMI.

I close this issue.

**Comment by alexxxdev** [comment]
> I switch to [Libre](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) OHM clone, they still support WMI.
thx, I will also try to use this
