### ISSUE TITLE
Unable to obtain information on Intel 12th gen NUC

### ISSUE THREAD

**Issue by xzona26** [hexagon-oss/openhardwaremonitor#51]
On my 12th gen  Alder Lake CPU (Intel N100), I can only obtain load information without temperature, frequency, and other information.
I am using version 0.10.5-alpha1 and have also tried version issue #43, but I am unable to obtain information.
<img width="776" alt="0702b0e9291ce84ecff22b79e67e5f0" src="https://github.com/hexagon-oss/openhardwaremonitor/assets/142763511/ca679b39-cb62-4be1-95dd-b1acc2e08027">

**Comment by pgrawehr** [comment]
This is probably caused by some unknown model type. Can you attach a report please (Use "File->Save Report")?

**Comment by xzona26** [comment]
[OpenHardwareMonitor.Report_20230825.txt](https://github.com/hexagon-oss/openhardwaremonitor/files/12433294/OpenHardwareMonitor.Report_20230825.txt)
Thanks for your reply，this is repo file。

**Comment by pgrawehr** [comment]
Thanks, I'll take a look.
