### ISSUE TITLE
.Net 8 - .Net 6 support ends soon

### ISSUE THREAD

**Issue by mardem1** [hexagon-oss/openhardwaremonitor#67]
Hi,

are there any plans to migrate to .Net 8 ?

.Net 6 support ends on Nov 12, 2024 - https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

kind regards

**Comment by pgrawehr** [comment]
I have plenty of to-do items in this repo, this is certainly one of them. However, other projects usually get more priority,  so this stays behind. I hope I remember in the next planning round.

**Comment by mardem1** [comment]
👍 thanks
